// 50 questions to capture user preferences and personality
export const QUESTIONS = [
  { id: "favorite_food", type: "text", text: "What is my favorite food?" },
  { id: "clothing_style", type: "text", text: "What style of clothes do I wear?" },
  { id: "like_spicy_food", type: "boolean", text: "Do I like spicy food?" },
  { id: "enjoy_puzzles", type: "boolean", text: "Do I enjoy puzzles?" },
  { id: "prefer_mornings", type: "boolean", text: "Am I a morning person?" },
  { id: "coffee_or_tea", type: "text", text: "Do I prefer coffee or tea?" },
  { id: "like_travel", type: "boolean", text: "Do I like to travel?" },
  { id: "prefer_beach", type: "boolean", text: "Do I prefer the beach?" },
  { id: "prefer_mountains", type: "boolean", text: "Do I prefer the mountains?" },
  { id: "like_cooking", type: "boolean", text: "Do I like to cook?" },
  { id: "like_reading", type: "boolean", text: "Do I like reading?" },
  { id: "favorite_music", type: "text", text: "What is my favorite music genre?" },
  { id: "like_podcasts", type: "boolean", text: "Do I like podcasts?" },
  { id: "like_movies", type: "boolean", text: "Do I like movies?" },
  { id: "favorite_movie_genre", type: "text", text: "What is my favorite movie genre?" },
  { id: "like_sports", type: "boolean", text: "Do I like sports?" },
  { id: "favorite_sport", type: "text", text: "What is my favorite sport?" },
  { id: "like_gaming", type: "boolean", text: "Do I like gaming?" },
  { id: "prefer_outdoors", type: "boolean", text: "Do I prefer the outdoors?" },
  { id: "like_animals", type: "boolean", text: "Do I like animals?" },
  { id: "have_pets", type: "boolean", text: "Do I have pets?" },
  { id: "like_art", type: "boolean", text: "Do I like art?" },
  { id: "favorite_color", type: "text", text: "What is my favorite color?" },
  { id: "like_learning", type: "boolean", text: "Do I like learning new things?" },
  { id: "enjoy_diy", type: "boolean", text: "Do I enjoy DIY projects?" },
  { id: "prefer_minimalism", type: "boolean", text: "Do I prefer minimalism?" },
  { id: "like_plants", type: "boolean", text: "Do I like plants?" },
  { id: "like_museums", type: "boolean", text: "Do I like museums?" },
  { id: "like_theater", type: "boolean", text: "Do I like theater?" },
  { id: "like_dancing", type: "boolean", text: "Do I like dancing?" },
  { id: "prefer_text_over_video", type: "boolean", text: "Do I prefer text over video?" },
  { id: "like_writing", type: "boolean", text: "Do I like writing?" },
  { id: "like_photography", type: "boolean", text: "Do I like photography?" },
  { id: "like_cycling", type: "boolean", text: "Do I like cycling?" },
  { id: "like_running", type: "boolean", text: "Do I like running?" },
  { id: "like_swimming", type: "boolean", text: "Do I like swimming?" },
  { id: "like_board_games", type: "boolean", text: "Do I like board games?" },
  { id: "like_coding", type: "boolean", text: "Do I like coding?" },
  { id: "like_history", type: "boolean", text: "Do I like history?" },
  { id: "like_science", type: "boolean", text: "Do I like science?" },
  { id: "like_technology", type: "boolean", text: "Do I like technology?" },
  { id: "like_fashion", type: "boolean", text: "Do I like fashion?" },
  { id: "like_trendy", type: "boolean", text: "Do I like trendy things?" },
  { id: "prefer_quiet", type: "boolean", text: "Do I prefer quiet places?" },
  { id: "like_large_groups", type: "boolean", text: "Do I like large groups?" },
  { id: "like_volunteering", type: "boolean", text: "Do I like volunteering?" },
  { id: "like_gardening", type: "boolean", text: "Do I like gardening?" },
  { id: "prefer_home", type: "boolean", text: "Do I prefer staying at home?" },
  { id: "like_city_life", type: "boolean", text: "Do I like city life?" },
  { id: "like_country_life", type: "boolean", text: "Do I like country life?" }
];